spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'  #adblock-nocoin-list
      - 'https://cdn.jsdelivr.net/gh/durablenapkin/scamblocklist/adguard.txt' #Scam Blocklist
      - 'https://someonewhocares.org/hosts/zero/hosts' #Dan Pollock's List
      - 'https://cdn.jsdelivr.net/gh/AdguardTeam/FiltersRegistry/filters/filter_15_DnsFilter/filter.txt' #AdGuard DNS filter
      - 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext' #Peter Lowe's List
      - 'https://abp.oisd.nl/basic/' #OISD Blocklist Basic
      #- 'https://adaway.org/hosts.txt' #AdAway Default Blocklist
      - 'https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker/data/hosts/spy.txt' #WindowsSpyBlocker
      #- 'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad-pc.txt' #HalfLife（pc）
      #- 'https://cdn.jsdelivr.net/gh/banbendalao/ADgk@master/ADgk.txt' #Adgk
      - 'https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt' #yhosts
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #大圣净化
      #- 'https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/trackers.list' #Domains classified as tracking or advertising
      - 'https://code.gitlink.org.cn/hacamer/AdRules/raw/branch/main/adguard-full.txt' #AdRules AdGuard Full List
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt' #adguard base
      #自用添加↓
      - 'https://anti-ad.net/easylist.txt' #name: anti-AD
      #- 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts' #name: StevenBlack/hosts规则
      - 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt' #name: AdGuard CNAME 伪装跟踪器列表
      - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' #name: AdGuard DNS filter
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt' #name: AdditionalFiltersCN
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' #name: ADgk 移动广告规则
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt' #name: 乘风 广告过滤规则
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt' #name: 乘风 视频过滤规则
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt' #name: HalfLife_合并自乘风视频广告过滤规则、EasylistChina、EasylistLite、CJX'sAnnoyance
      - 'https://adaway.org/hosts.txt' #name: AdAway 官方的去广告 Host 规则
      - 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' #name: 去除禁止广告拦截提示规则
      - 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt' #name: Yhosts规则
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #name: 大圣净化（针对国内视频）
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt' #name: 杏稍AdRules DNS List
      - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt' #name: 知乎 普通版
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #name: 秋风广告规则,针对Android广告
      - 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.txt' #name: uBlock filters
      - 'https://ublockorigin.pages.dev/filters/badware.txt' #name: uBlock filters – Badware risks
      - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/privacy.txt' #name: uBlock filters – Privacy
      - 'https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt' #name: uBlock filters – Quick fixes
      - 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/resource-abuse.txt' #name: uBlock filters – Resource abuse
      - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/unbreak.txt' #name: uBlock filters – Unbreak
      - 'https://filters.adtidy.org/extension/ublock/filters/11.txt' #name: AdGuard Mobile Ads移动设备
      #神殿规则
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/all.txt' #name: BlueSkyXN主规则1
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/skyrules.txt' #name: BlueSkyXN主规则2
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/ok.txt' #name: BlueSkyXN主规则3
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/manhua.txt' #name: BlueSkyXN动漫&漫画网站定制规则1
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/manhua-plus.txt' #name: BlueSkyXN动漫&漫画网站定制规则2
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/manhua-max.txt' #name: BlueSkyXN动漫&漫画网站定制规则3
      #- 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/ubcn.txt' #name: BlueSkyXNUBCN补充规则
      - 'https://easylist-downloads.adblockplus.org/easylist.txt' #name: EasyList
      - 'https://easylist-downloads.adblockplus.org/easylistchina.txt' #name: EasyList China
      - 'https://easylist-downloads.adblockplus.org/easyprivacy.txt' #name: EasyPrivacy
      - 'https://easylist-downloads.adblockplus.org/easylist-cookie.txt' #name: EasyList Cookie List
      - 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt' #name: Anti-AD
      - 'https://www.i-dont-care-about-cookies.eu/abp/' #name: I don't care about cookies
      - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt' #name: Zhihu Filter Basic
      - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu-strict.txt' #name: Zhihu Filter Strict
      - 'https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts' #name: 1024_hosts
      - 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt' #name: YHost
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt' #name: CJX's Annoyance List
      - 'https://easylist-downloads.adblockplus.org/easylistchina.txt' #name: EasyList China
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #name: 秋风
      - 'https://lingmao.655618.xyz/jiaoben/adg/%E6%99%B4%E9%9B%85/hosts.php' #name: 晴雅
      - 'https://lingmao.655618.xyz/jiaoben/adg/%E6%99%B4%E9%9B%85/black.php' #name: 晴雅黑名单
      - 'https://lingmao.655618.xyz/jiaoben/adg/%E6%99%B4%E9%9B%85/dns.php' #name: 晴雅DNS
      #- 'https://nsfw.oisd.nl/' #name: nsfw
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt' #name: AdGuard Chinese filter
      - 'https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/adblock.txt' #name: 1Hosts (Lite)
      - 'https://www.malwaredomainlist.com/hostslist/hosts.txt' #name: Malware Domain List
      - 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts' #name: StevenBlack
      - 'https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt' #name: iOSAdblockList
      - 'https://raw.githubusercontent.com/Maasea/sgmodule/master/Bilibili.Helper.sgmodule' #name: 去bilibili广告
      - 'https://raw.githubusercontent.com/Maasea/sgmodule/master/KeepAds.sgmodule' #name: 去keep广告
      - 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt' #name: NoAppDownload
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt' #name: ADgk 屏蔽百家号
      - 'https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list' #name: The Big List of Hacked Malware Web Sites
      - 'https://raw.githubusercontent.com/sdars/AdGuard-Rule/main/rule/mylist.txt' #name: 神殿
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
        #- HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
